### ISSUE TITLE
WHEEL MODE AND SPEED

### ISSUE THREAD

**Issue by sasilva1998** [MomsFriendlyRobotCompany/pyxl320#5]
I am trying to change the mode to wheel_mode, and then make it turn with an specific speed, however when I use the following method:
~~~~ python
pkt=Packet.makeControlModePacket(1,1)
~~~~
and then send it trough serial, the xl320's red led starts flickering and looks like it blocks until it resets.
Does anyone know what the problem is?

**Comment by sasilva1998** [comment]
Nevermind, the problem was that, before trying to change the control mode, had to disable torque. Also needed to clarify that with the makeWritePacket() generic method, if the register is a single byte register, le() is not needed to be used in the params, otherwise the packet isn't right.

**Comment by walchko** [comment]
thanks for the feedback! For the last 1-2 years I have mainly been using the AX-12 servos, but just carrying along the code for my old work with the xl320's. Eventually I want to combine all of the code into one code base, but I haven't had time to really flush that out fully.

Have a great day!

**Comment by sasilva1998** [comment]
thanks to you for the work, needed it cause wanted to make a suitable version to work with micropython, it still needs a bit more work, anyway nice work, here is  the link where I have used what you developed, although sorry I didn't fork it, pretty new in this. Now I am looking fordward to doing the same with the AX-12

https://github.com/FunPythonEC/xl320_upy
